config/routes.rb
Rails.application.routes.draw do
  resource :access_token, only: [:new]

  resources :trackers, only: [:index, :new]
  resources :account_trackers, only: [:show, :create, :destroy]
  resources :hashtag_trackers, only: [:show, :create, :destroy]

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  authenticated do
    root to: 'trackers#index', as: :authenticated_root
  end

  root to: redirect('/welcome')
end

app/models/access_token.rb
class AccessToken < ApplicationRecord
  belongs_to :user
  validates :value, presence: true
  attr_encryptor :value, key: Rails.application.secrets.access_token_key
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :account_trackers
  validates :instagram_uid, presence: true, uniqueness: true
  validates :name, presence: true
end

app/models/account_tracker.rb
class AccountTracker < ApplicationRecord
  belongs_to :account
  belongs_to :user
  validates :account, uniqueness: { scope: :user }
  alias_attribute :name, :account
  
  def access_token_value
    user.access_token.value
  end

  def name
    account.name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :hashtag_trackers
  validates :name, presence: true, uniqueness: true
end

app/models/hashtag_tracker.rb
class HashtagTracker < ApplicationRecord
  belongs_to :hashtag
  belongs_to :user
  validates :hashtag, uniqueness: { scope: :user }

  def access_token_value
    user.access_token.value
  end

  def name
    hashtag.name
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :access_token
  has_many :account_trackers
  has_many :hashtag_trackers
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :lockable,
         :omniauthable, omniauth_providers: [ :instagram ]

  class << self
    def from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create
    end

    def new_with_session(params, session)
      super.tap do |user|
        data = session["devise.instagram_data"]
        set_instagram_attrs(user, data) if data
      end
    end

    def set_instagram_attrs(user, data)
      user.build_access_token(value: data.dig('credentials', 'token'))
      user.provider = 'instagram'
      user.uid = data['uid']
      user.instagram_name = data.dig 'info', 'nickname'
    end
  end

  def access_token_value
    access_token.value
  end
end

app/controllers/access_tokens_controller.rb
class AccessTokensController < ApplicationController
  skip_before_action :validate_instagram_access_token
  skip_after_action :verify_authorized, only: :new

  def new
    redirect_to root_path if current_user.access_token.present?
  end
end

app/controllers/account_trackers_controller.rb
class AccountTrackersController < ApplicationController
  skip_after_action :verify_authorized, only: :create

  def show
    tracker = AccountTracker.find(params[:id])
    authorize tracker
    @presenter = AccountTrackers::ShowPresenter.new(tracker)
  end

  def create
    result = CreateAccountTracker.call(merged_params)
    tracker = result.tracker

    if result.success?
      flash[:success] = I18n.t('trackers.create.success', name: tracker.name)
      redirect_to account_tracker_path(result.tracker)
    else
      flash[:alert] = result.message
      redirect_to new_tracker_path
    end
  end

  def destroy
    tracker = AccountTracker.find(params[:id])
    authorize tracker

    if tracker.destroy
      flash[:success] = I18n.t('trackers.destroy.success', name: tracker.name)
    else
      flash[:alert] = I18n.t('trackers.destroy.failure', name: tracker.name)
    end
    redirect_to trackers_path
  end

  private

  def merged_params
    tracker_params.merge(user: current_user)
  end

  def tracker_params
    params.require(:tracker).permit(:account, :name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index
  skip_after_action :verify_authorized, if: :devise_controller?

  before_action :validate_instagram_access_token
  skip_before_action :validate_instagram_access_token, if: :devise_controller?

  before_action :set_raven_context

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def set_raven_context
    Raven.user_context(id: current_user.id) if current_user.present?
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end

  def validate_instagram_access_token
    if current_user.access_token.blank?
      redirect_to new_access_token_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_after_action :verify_authorized, only: [:show]

  def show
  end
end

app/controllers/hashtag_trackers_controller.rb
class HashtagTrackersController < ApplicationController
  def show
    tracker = HashtagTracker.find_by_param(params[:id])
    authorize tracker
    @presenter = HashtagTrackers::ShowPresenter.new(tracker)
  end

  def destroy
    tracker = HashtagTracker.find_by_param(params[:id])
    authorize tracker

    if tracker.destroy
      flash[:success] = I18n.t('trackers.destroy.success', name: tracker.name)
    else
      flash[:alert] = I18n.t('trackers.destroy.failure', name: name)
    end
    redirect_to trackers_path
  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  skip_after_action :verify_authorized, only: [:new]
  skip_after_action :verify_policy_scoped, only: :index

  def index
    account_trackers = AccountTrackerDecorator.wrap(current_user.account_trackers)
    hashtag_trackers = HashtagTrackerDecorator.wrap(current_user.hashtag_trackers)
    @trackers = account_trackers + hashtag_trackers
  end

  def new
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def instagram
    find_or_create_user
    sign_in_or_register
  end

  def failure
    redirect_to root_path
  end

  private

  def find_or_create_user
    if current_user.blank?
      @user = User.from_omniauth(request.env["omniauth.auth"])
    else
      @user = current_user
      User.set_instagram_attrs(@user, request.env['omniauth.auth'])
      @user.save!
      flash[:success] = I18n.t('omniauth.instagram.connected', account: @user.instagram_name)
    end
  end

  def sign_in_or_register
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      flash[:notice] = I18n.t('omniauth.instagram.create_account')
      session["devise.instagram_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def print_nav_label(label)
    label.titleize
  end

  def number_to_human(number)
    super(number, format: '%n%u', units: { thousand: 'K', million: 'M', billion: 'B' })
  end

  def print_title(title)
    title.present? ? title : t("titles.#{controller_name}")
  end

  def success
    flash[:success]
  end

  def title(title)
    content_for :title, title.to_s
  end
end

app/views/access_tokens/new.html.erb
<% title I18n.t('titles.account_setup') %>

<div class="mdl-cell mdl-cell--2-col mdl-cell--1-col-tablet"></div>
<div class="mdl-card mdl-shadow--4dp mdl-cell mdl-cell--8-col">
  <div class="mdl-card__title mdl-color--primary" style="height:100px">
    <h2 class="mdl-card__title-text">
      <%= t('access_tokens.connect.instagram') %>
    </h2>
  </div>
  <div class="mdl-card__supporting-text">
    <%= t('.connect_message') %>
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <%=
      link_to t('access_tokens.connect.instagram'),
      omniauth_authorize_path(:user, :instagram),
      class: "mdl-button mdl-js-button mdl-js-ripple-effect"
    %>
  </div>
</div>

<div class="mdl-cell mdl-cell--2-col mdl-cell--1-col-tablet"></div>

app/views/account_trackers/_post.html.erb
<% image_src = post["images"]["standard_resolution"]["url"] %>
<% likes = post["likes"]["count"] %>
<% comments = post["comments"]["count"] %>
<% link = post["link"] %>

<div class="mdl-cell mdl-cell--4-col mdl-cell--4-col-tablet mdl-cell--2-col-phone mdl-card mdl-shadow--4dp post"
  data-link=<%= link %>
  style="background-image: url('<%= image_src %>')">
  <div class="mdl-card__title mdl-card--expand"></div>
  <div class="mdl-card__actions">
    <i class="material-icons">favorite</i><%= number_to_human(likes) %>
    <div class="mdl-layout-spacer"></div>
    <i class="material-icons">comment</i><%= number_to_human(comments) %>
  </div>
</div>

app/views/account_trackers/show.html.erb
<% title @presenter.name %>

<% content_for :page_options do %>
  <%=
    link_to account_tracker_path(@presenter.tracker),
    class: "mdl-menu__item",
    method: :delete,
    data: { confirm: I18n.t('trackers.tracker.delete_message') } do %>
    <%= t('page_options.delete').titleize %>
  <% end %>
<% end %>

<section class="mdl-cell mdl-cell--12-col mdl-cell--8-col-tablet mdl-cell--8-col-phone">
  <h3>Recent Posts</h3>
  <div class="mdl-grid mdl-grid--nested">
    <%= render partial: 'post', collection: @presenter.recent_posts %>
  </div>
</section>

<script type='text/javascript'>
  setCardHeight();
  
  $(document).ready(function () {
    createLinks();
  });

  $(window).on("resize", function() {
    setCardHeight();
  });
</script>

app/views/dashboard/show.html.erb
<% title t('titles.dashboard') %>

<div class="mdl-cell mdl-cell--12-col">
  <h1><%= t(:hello) %></h1>
</div>

<div class="mdl-cell mdl-cell--12-col">
  <ul>
    <li>Tracker Index</li>
    <li>Search Tool (like Keyhole)</li>
  </ul>
</div>

app/views/hashtag_trackers/_post.html.erb
<% image_src = post["images"]["standard_resolution"]["url"] %>
<% likes = post["likes"]["count"] %>
<% comments = post["comments"]["count"] %>
<% link = post["link"] %>

<div class="mdl-cell mdl-cell--6-col mdl-cell--2-col-tablet mdl-cell--2-col-phone mdl-card mdl-shadow--4dp post"
  data-link=<%= link %>
  style="background-image: url('<%= image_src %>')">
  <div class="mdl-card__title mdl-card--expand"></div>
  <div class="mdl-card__actions">
    <i class="material-icons">favorite</i><%= number_to_human(likes) %>
    <div class="mdl-layout-spacer"></div>
    <i class="material-icons">comment</i><%= number_to_human(comments) %>
  </div>
</div>

app/views/hashtag_trackers/_user.html.erb
<% username = user["username"] %>
<% image_src = user["profile_picture"] %>
<% followers = user["counts"]["followed_by"] %>
<% posts = user["counts"]["media"] %>

<div class="mdl-cell mdl-cell--4-col mdl-cell--2-col-tablet mdl-cell--2-col-phone mdl-card mdl-shadow--4dp user"
  data-link=<%= "https://www.instagram.com/#{username}/" %>
  style="background-image: url('<%= image_src %>')">
  <div class="mdl-card__title mdl-card--expand"></div>
  <div class="mdl-card__actions">
    <i class="material-icons">group</i><%= number_to_human(followers) %>
  </div>
</div>

app/views/hashtag_trackers/show.html.erb
<% title @presenter.name %>

<% content_for :page_options do %>
  <%=
    link_to hashtag_tracker_path(@presenter.tracker),
    class: "mdl-menu__item",
    method: :delete,
    data: { confirm: I18n.t('trackers.tracker.delete_message') } do %>
    <%= t('page_options.delete').titleize %>
  <% end %>
<% end %>

<section class="mdl-cell mdl-cell--8-col mdl-cell--8-col-tablet mdl-cell--8-col-phone">
  <h3>Recent Posts</h3>
  <div class="mdl-grid mdl-grid--nested">
    <%= render partial: 'post', collection: @presenter.recent_posts %>
  </div>
</section>

<section class="mdl-cell mdl-cell--4-col mdl-cell--8-col-tablet mdl-cell--8-col-phone">
  <h3>Recent Users</h3>
  <div class="mdl-grid mdl-grid--nested">
    <%= render partial: 'user', collection: @presenter.recent_users %>
  </div>
</section>

<script type='text/javascript'>
  setCardHeight();

  $(document).ready(function () {
    createLinks();
  });

  $(window).on("resize", function() {
    setCardHeight();
  });
</script>

app/views/layouts/_app_flash_message.html.erb
<div class="mdl-cell mdl-cell--12-col flash">
  <% if alert.present? %>
    <div class="message alert"><%= alert %></div>
  <% end %>
  
  <% if notice.present? %>
    <div class="message notice"><%= notice %></div>
  <% end %>

  <% if success.present? %>
    <div class="message success"><%= success %></div>
  <% end %>
</div>

app/views/layouts/_devise_flash_message.html.erb
<div class="col-sm-12">
  <% if alert.present? %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>
  
  <% if notice.present? %>
    <div class="alert alert-info"><%= notice %></div>
  <% end %>

  <% if success.present? %>
    <div class="alert alert-success"><%= success %></div>
  <% end %>
</div>

app/views/layouts/_flash_message.html.erb
<div class="mdl-cell mdl-cell--12-col flash">
  <% if notice.present? %>
    <div class="message notice"><%= notice %></div>
  <% end %>

  <% if alert.present? %>
    <div class="message alert"><%= alert %></div>
  <% end %>

  <% if success.present? %>
    <div class="message success"><%= success %></div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="mdl-mini-footer">
  <div class="mdl-mini-footer__left-section">
    <div class="mdl-logo"><%= t('company_name') %></div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= print_title yield(:title) %></title>

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.grey-blue.min.css" />
  <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g=" crossorigin="anonymous"></script>
</head>

app/views/layouts/_header.html.erb
<header id="header" class="mdl-layout__header">
  <div class="mdl-layout__header-row">
    <span class="mdl-layout-title"><%= print_title yield(:title) %></span>
    <%= render 'layouts/page_options' if content_for? :page_options %>
  </div>
</header>

app/views/layouts/_nav_drawer.html.erb
<div id="main-nav-drawer" class="mdl-layout__drawer">
  <header class="drawer-header">
    <div class="dropdown">
      <span><%= current_user.email.truncate(25) %></span>
      <div class="mdl-layout-spacer"></div>
      <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
        <i class="material-icons" role="presentation">arrow_drop_down</i>
        <span class="visuallyhidden">User </span>
      </button>
      <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="accbtn">
        <li class="mdl-menu__item">
          <%= link_to destroy_user_session_path, class: 'mdl-navigation__link', method: :delete do %>
            Log Out
          <% end %>
        </li>
      </ul>
    </div>
  </header>

  <nav id="main-nav" class="mdl-navigation">
    <%= link_to root_path, class: 'mdl-navigation__link' do %>
      <i class="material-icons" role="presentation">dashboard</i>
      <%= print_nav_label t('nav.dashboard') %>
    <% end %>
  </nav>
</div>

app/views/layouts/_page_options.html.erb
<div class="mdl-layout-spacer"></div>
<button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="page-options">
  <i class="material-icons">more_vert</i>
</button>
<ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="page-options">
  <%= yield :page_options %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body class="<%= "#{controller_name} #{action_name}" %>">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
      <%= render 'layouts/header' %>
      <%= render 'layouts/nav_drawer' %>

      <main id="main-content" class="mdl-layout__content">
        <div class="grid-wrapper">
          <div class="mdl-grid">
            <%= render 'layouts/app_flash_message' %>
            <%= yield %>
          </div>
        </div>

        <%= render 'layouts/footer' %>
      </main>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g=" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag 'devise', media: 'all' %>

  <body class="devise">
    <%= render file: 'site/source/_nav' %>
    <div class="main-wrapper">
      <%= render 'layouts/devise_flash_message' %>
      <div class="col-sm-4"></div>
      <div class="col-sm-4 content">
        <%= yield %>
      </div>
      <div class="col-sm-4"></div>
    </div>

    <footer class="text-center">
      <%= render file: 'site/source/_footer_nav' %>
    </footer>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-51894707-10', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>

app/views/trackers/_tracker.html.erb
<div class="mdl-cell mdl-cell-4 mdl-card mdl-shadow--4dp">
  <div class="mdl-card__title mdl-color--primary mdl-card--expand">
    <h2 class="mdl-card__title-text">
      <%= tracker.name %>
    </h2>
  </div>
  <div class="mdl-card__actions">
    <%= link_to tracker.show_path, class: "mdl-button mdl-js-button mdl-js-ripple-effect mdl-color--accent" do %>
      <%= t('.show') %>
    <% end %>

    <div class="mdl-layout-spacer"></div>

    <%=
      link_to tracker.delete_path,
      class: "mdl-button mdl-js-button mdl-js-ripple-effect",
      method: :delete,
      data: { confirm: I18n.t('trackers.tracker.delete_message') } do %>
      <%= t('.delete').titleize %>
    <% end %>
  </div>
</div>

app/views/trackers/index.html.erb
<% title t('titles.trackers') %>

<%= render partial: 'tracker', collection: @trackers %>
<% if @trackers.empty? %>
  <div class="mdl-cell mdl-cell--12-col">
    <h1>Hey there...</h1>
    <p style="font-size: 1.2em; font-weight:200">
      It looks like you don't have any trackers setup yet. To create a tracker,
      use the add button in the bottom right.
    </p>
  </div>
<% end %>

<%= link_to new_tracker_path, class: "mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--6dp new" do %>
  <i class="material-icons" role="presentation">add</i>
  <span class="visuallyhidden">Add</span>
<% end %>

app/views/trackers/new.html.erb
<div class="mdl-cell mdl-cell--2-col mdl-cell--1-col-tablet"></div>
<div class="mdl-card mdl-shadow--4dp mdl-cell mdl-cell--8-col">
  <div class="mdl-card__title mdl-color--primary">
    <h2 class="mdl-card__title-text"><%= t('.form').titleize %></h2>
  </div>
  <%= form_tag trackers_path, class: 'trackers' do %>
    <div class="mdl-card__supporting-text">
      <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label">
        <select id="type" class="mdl-selectfield__select">
          <option value="hashtag" selected>Hashtag</option>
          <option value="account">Account</option>
        </select>
        <div class="mdl-selectfield__icon"><i class="material-icons">arrow_drop_down</i></div>
        <label class="mdl-selectfield__label" for="type">Type</label>
      </div>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= text_field_tag 'tracker[name]', nil, class: 'mdl-textfield__input' %>
        <%= label_tag 'tracker[name]', t('defs.name'), class: 'mdl-textfield__label' %>
      </div>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <%= submit_tag t('.create').titleize, class: "mdl-button mdl-js-button mdl-js-ripple-effect" %>
    </div>
  <% end %>
</div>
<div class="mdl-cell mdl-cell--2-col mdl-cell--1-col-tablet"></div>

<script type="text/javascript">
  setAction('hashtag');

  $(document).ready(function (){
    $('#type').change(function() {
      var type = $(this).val();
      setAction(type);
    });
  });
</script>